repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
    - id: black
      language_version: python3.13
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.0
  hooks:
    - id: mypy
      additional_dependencies: ["types-requests"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
